name: ososs
description: A Flutter app that is used for a technical challenge.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # Widgets that make it easy to integrate blocs and cubits into Flutter. Built to work with package:bloc.
  flutter_bloc: ^8.1.3
  # A wrapper around InheritedWidget to make them easier to use and more reusable.
  provider: ^6.0.5
  # A powerful HTTP client for Dart/Flutter, which supports global configuration, interceptors, FormData, request cancellation, file uploading/downloading, timeout, and custom adapters etc.
  dio: ^5.1.2
  # Pretty Dio logger is a Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.3.1
  # A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.2.0
  # A package provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0
  # a widget provided to the flutter scroll component drop-down refresh and pull up load.support android and ios.
  pull_to_refresh_flutter3: ^2.0.1
  # 🔙 Swipe to navigate back and admire beautifully morphing widgets.
  swipeable_page_route: ^0.2.6
  # Draw SVG files using Flutter.
  flutter_svg: ^1.1.5
  # A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.6.1
  # Code generation for immutable classes with simple syntax
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Change native code splash
  flutter_native_splash: ^2.2.9
  # A command-line tool which simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: ^0.9.3
   # A build system for Dart code generation and modular compilation
  build_runner: ^2.1.11
  # Dependency injection code generator
  injectable_generator: ^1.5.3
  # Freezed package code generator
  freezed: ^2.0.3+1
  # Used in freezed package
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
